export const NAME_SPACE = "Home";

export const GET_ITEM = NAME_SPACE + "_GET_ITEM";
export const APPLY_PICKUP_DISCOUNT = NAME_SPACE + "_APPLY_PICKUP_DISCOUNT";
export const APPLY_PROMO_CODE = NAME_SPACE + "_APPLY_PROMO_CODE";
